#dynamic create disk
#https://docs.microsoft.com/en-us/azure/aks/azure-disk-csi#shared-disk

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-dolos
  labels:
    app: dolos
    usecase: azdisk-readwritelocal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dolos
      usecase: azdisk-readwritelocal
  template:
    metadata:
      labels:
        app: dolos
        usecase: azdisk-readwritelocal
    spec:
      containers:
      - name: dolos
        image: acrwanderer.azurecr.io/wanderer:dolos
        ports:
        - containerPort: 8000
        volumeMounts:
          - name: azdiskstatic
            mountPath: /mnt/azdisk
        livenessProbe:
          httpGet:
            path: /ready
            port: 8000
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 8
          periodSeconds: 30
        env:
          - name: Port
            valueFrom:
              configMapKeyRef:
                key: Port
                name: configmap-dolos
          - name: AzDiskMountFilePath
            valueFrom:
              configMapKeyRef:
                key: AzDiskMountFilePath
                name: configmap-dolos
          #TODO - MongoConnstring from secret
      volumes:
      - name: azdiskstatic
        azureDisk:
          kind: Managed
          cachingMode: None
          readOnly: false
          fsType: ext4
          diskName: azdisk-static-wanderer
          diskURI: /subscriptions/ee611083-4581-4ba1-8116-a502d4539206/resourcegroups/rg-public-kube/providers/Microsoft.Compute/disks/azdisk-static-wanderer
