#dynamic create disk
#https://docs.microsoft.com/en-us/azure/aks/azure-disk-csi#shared-disk

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-dolos
  labels:
    app: dolos
    solution: dolos #istio
    version: v1 #istio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dolos
      version: v1 #istio
  template:
    metadata:
      labels:
        app: dolos
        version: v1 #istio
      annotations:
        prometheus.io/scrape: "true"   # istio: determines if a pod should be scraped. Set to true to enable scraping.
        prometheus.io/path: /metrics # istio: determines the path to scrape metrics at. Defaults to /metrics.
        prometheus.io/port: "8000"  # istio: determines the port to scrape metrics at. Defaults to 80.
    spec:
      containers:
      - name: dolos
        imagePullPolicy: Always
        image: acrwanderer.azurecr.io/wanderer:dolos-0.1
        ports:
        - containerPort: 8000

        envFrom:
          - configMapRef:
              name: configmap-dolos

        volumeMounts:
          - name: azdiskstatic
            mountPath: /mnt/azdisk

        livenessProbe:
          httpGet:
            path: /ready
            port: 8000
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 8
          periodSeconds: 30
          
      volumes:
      - name: azdiskstatic
        azureDisk:
          kind: Managed
          cachingMode: None
          readOnly: false
          fsType: ext4
          diskName: azdisk-static-wanderer
          diskURI: /subscriptions/ee611083-4581-4ba1-8116-a502d4539206/resourcegroups/rg-public-kube/providers/Microsoft.Compute/disks/azdisk-static-wanderer
