#dynamic create disk
#https://docs.microsoft.com/en-us/azure/aks/azure-disk-csi#shared-disk

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-ymir
  labels:
    app: ymir
    usecase: azdisk-readwritelocal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ymir
      usecase: azdisk-readwritelocal
  template:
    metadata:
      labels:
        app: ymir
        usecase: azdisk-readwritelocal
    spec:
      containers:
      - name: ymir
        imagePullPolicy: Always
        image: acrwanderer.azurecr.io/wanderer:ymir
        ports:
        - containerPort: 8000
        envFrom:
          - configMapRef:
              name: configmap-ymir

        livenessProbe:
          httpGet:
            path: /ready
            port: 8000
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 8
          periodSeconds: 30